loc_ptgl = ("","")

loc_wxgl = ("","")
loc_jxgl = ("","")
loc_wxsz = ("","")
loc_yygl = ("","")
loc_yhgl = ("","")
loc_zxgl = ("","")
loc_tzgl = ("","")
loc_hyzx = ("","")


loc_ddjs = ("","")
loc_ddjl = ("","")
loc_ddtj = ("","")
loc_jsgl = ("","")
loc_cwgl = ("","")
loc_qtjl = ("","")
loc_skjs = ("","")
loc_zffs = ("","")
loc_srtj = ("","")
loc_bmtj = ("","")

loc_khfw = ("xpath",".//*[@title='客户服务']")
loc_yhfw = ("link text","用户服务")
loc_wxfu = ("","")
loc_shhz = ("","")
loc_yhfk = ("","")
loc_sjsh = ("","")
loc_kcfw = ("","")

loc_yyzx = ("","")

loc_sjfx = ("","")

loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
loc_ = ("","")
